### ISSUE TITLE
Saving Isn't Working.

### ISSUE THREAD

**Issue by NGCMan** [NGCMan/NGC-Man-s-Game#2]
Someone, if you're out there, please help!

**Comment by twufu** [comment]
Hi, I am new to programming and I am going to try and make a save mechanism that works. I probably wont do well but ill try 👍

**Comment by NGCMan** [comment]
Thanks.

**Comment by twufu** [comment]
I think I made some code that might work (I'm new to GitHub, don't know better ways to do this):

function save() {

localStorage.setItem('coins', JSON.stringify(coins));

localStorage.setItem('incomes', JSON.stringify(incomes));

localStorage.setItem('costs', JSON.stringify(costs));

localStorage.setItem('costmult', JSON.stringify(costmult));

localStorage.setItem('amounts', JSON.stringify(amounts));

localStorage.setItem('multipliers', JSON.stringify(multipliers));

localStorage.setItem('progress', JSON.stringify(progress));

}

function load() {

coins = JSON.parse(localStorage.getItem('coins'));

incomes = JSON.parse(localStorage.getItem('incomes'));

costs = JSON.parse(localStorage.getItem('costs'));

costmult = JSON.parse(localStorage.getItem('costmult'));

amounts = JSON.parse(localStorage.getItem('amounts'));

multipliers = JSON.parse(localStorage.getItem('multipliers'));

progress = JSON.parse(localStorage.getItem('progress'));

}

edit: Try binding these commands to save game and load game buttons. Also I'm not 100% sure if the functions work.

**Comment by NGCMan** [comment]
It works perfectly! Thank you so much!
