### ISSUE TITLE
Break Infinity Isn't Working.

### ISSUE THREAD

**Issue by NGCMan** [NGCMan/NGC-Man-s-Game#3]
The numbers don't go above 1e308.

**Comment by twufu** [comment]
Try Decimal.js, It takes a while to set up and learn how to use but it works!
Clicker heroes, swarm sim and lots of clicker games use it.

**Comment by twufu** [comment]
For each number you use Decimal(number), to add and stuff do Decimal(number).add(number). There is also lots more commands like that.

**Comment by NGCMan** [comment]
I'm resolving this, as I've rewritten this game long ago, and it works in the rewrite.
